version: '3.8'

services:
  frontend:
    image: my-frontend-image
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:80"  
    depends_on:
      - backend

  backend:
    image: my-backend-image
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"